---
fixtures:
  forge_modules:
    cron_core:
      repo: "puppetlabs/cron_core"
      ref: "1.1.0"
    dsc:
      repo: "puppetlabs/dsc"
      ref: "1.9.4"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "8.1.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.1.0"
